import img from '../../assets/images/Home/HERO_FINAL.png'; // Importar la imagen
//arreglo para los trabajos
export const trabajos = [
  {
    titulo: 'Desarrollador Frontend',
    prestamista: 'Juan Pérez',
    imagen: img,
    categoria: 'Tecnología',
    alcaldia: 'Cuauhtémoc',
    descripcion: 'Buscamos un desarrollador frontend con experiencia en React y JavaScript.',
    fecha: '2023-10-01',
    incluyeMateriales: true,
    garantia: '15 días',
    direccionReferencia: 'Av. Paseo de la Reforma 123, Col. Juárez, CDMX',
    modalidadesCobro: ['Por hora', 'Por Proyecto'],
    costo: 5000,
    disponibilidad: [
      { dia: 'Lunes', horario: '9:00 AM - 5:00 PM' },
      { dia: 'Martes', horario: '9:00 AM - 5:00 PM' },
    ],
    evidencias: [
      img,
      img,
      img,
    ],
  },
  {
    titulo: 'Diseñador Gráfico',
    prestamista: 'María López',
    imagen: img,
    categoria: 'Diseño',
    alcaldia: 'Benito Juárez',
    descripcion: 'Se requiere diseñador gráfico con habilidades en Adobe Photoshop e Illustrator.',
    fecha: '2023-10-02',
    incluyeMateriales: false,
    garantia: null,
    direccionReferencia: 'Av. Insurgentes Sur 456, Col. Del Valle, CDMX',
    modalidadesCobro: ['Por Proyecto'],
    costo: 8000,
    disponibilidad: [
      { dia: 'Miércoles', horario: '10:00 AM - 4:00 PM' },
      { dia: 'Jueves', horario: '10:00 AM - 4:00 PM' },
    ],
    evidencias: [
      'https://via.placeholder.com/150',
      'https://via.placeholder.com/150',
    ],
  },
  {
    titulo: 'Gerente de Proyectos',
    prestamista: 'Carlos García',
    imagen: img,
    categoria: 'Gestión',
    alcaldia: 'Iztapalapa',
    descripcion: 'Gerente de proyectos con experiencia en metodologías ágiles y gestión de equipos.',
    fecha: '2023-10-03',
    incluyeMateriales: true,
    garantia: '30 días',
    direccionReferencia: 'Calle 123, Col. Centro, CDMX',
    modalidadesCobro: ['Por mes'],
    costo: 20000,
    disponibilidad: [
      { dia: 'Lunes a Viernes', horario: '9:00 AM - 6:00 PM' },
    ],
    evidencias: [
      'https://via.placeholder.com/150',
      'https://via.placeholder.com/150',
      'https://via.placeholder.com/150',
      'https://via.placeholder.com/150',
    ],
  },
  {
    titulo: 'Analista de Datos',
    prestamista: 'Ana Martínez',
    imagen: img,
    categoria: 'Análisis',
    alcaldia: 'Coyoacán',
    descripcion: 'Buscamos un analista de datos con experiencia en SQL y herramientas de visualización.',
    fecha: '2023-10-04',
    incluyeMateriales: false,
    garantia: null,
    direccionReferencia: null,
    modalidadesCobro: ['Por hora'],
    costo: 300,
    disponibilidad: [
      { dia: 'Sábado', horario: '10:00 AM - 2:00 PM' },
    ],
    evidencias: [
      'https://via.placeholder.com/150',
    ],
  },
  {
    titulo: 'Especialista en Marketing Digital',
    prestamista: 'Luis Hernández',
    imagen: img,
    categoria: 'Marketing',
    alcaldia: 'Gustavo A. Madero',
    descripcion: 'Especialista en marketing digital con experiencia en SEO y campañas de publicidad online.',
    fecha: '2023-10-05',
    incluyeMateriales: true,
    garantia: '7 días',
    direccionReferencia: 'Av. Eduardo Molina 789, Col. Aragón, CDMX',
    modalidadesCobro: ['Por día'],
    costo: 1500,
    disponibilidad: [
      { dia: 'Lunes a Viernes', horario: '8:00 AM - 4:00 PM' },
    ],
    evidencias: [
      'https://via.placeholder.com/150',
      'https://via.placeholder.com/150',
    ],
  },
  {
    titulo: 'Desarrollador Frontend',
    prestamista: 'Juan Pérez',
    imagen: img,
    categoria: 'Tecnología',
    alcaldia: 'Cuauhtémoc',
    descripcion: 'Buscamos un desarrollador frontend con experiencia en React y JavaScript.',
    fecha: '2023-10-01',
    incluyeMateriales: true,
    garantia: '15 días',
    direccionReferencia: 'Av. Paseo de la Reforma 123, Col. Juárez, CDMX',
    modalidadesCobro: ['Por hora', 'Por Proyecto'],
    costo: 5000,
    disponibilidad: [
      { dia: 'Lunes', horario: '9:00 AM - 5:00 PM' },
      { dia: 'Martes', horario: '9:00 AM - 5:00 PM' },
    ],
    evidencias: [
      'https://via.placeholder.com/150',
      'https://via.placeholder.com/150',
      'https://via.placeholder.com/150',
    ],
  },
  {
    titulo: 'Diseñador Gráfico',
    prestamista: 'María López',
    imagen: img,
    categoria: 'Diseño',
    alcaldia: 'Benito Juárez',
    descripcion: 'Se requiere diseñador gráfico con habilidades en Adobe Photoshop e Illustrator.',
    fecha: '2023-10-02',
    incluyeMateriales: false,
    garantia: null,
    direccionReferencia: 'Av. Insurgentes Sur 456, Col. Del Valle, CDMX',
    modalidadesCobro: ['Por Proyecto'],
    costo: 8000,
    disponibilidad: [
      { dia: 'Miércoles', horario: '10:00 AM - 4:00 PM' },
      { dia: 'Jueves', horario: '10:00 AM - 4:00 PM' },
    ],
    evidencias: [
      'https://via.placeholder.com/150',
      'https://via.placeholder.com/150',
    ],
  },
  {
    titulo: 'Gerente de Proyectos',
    prestamista: 'Carlos García',
    imagen: img,
    categoria: 'Gestión',
    alcaldia: 'Iztapalapa',
    descripcion: 'Gerente de proyectos con experiencia en metodologías ágiles y gestión de equipos.',
    fecha: '2023-10-03',
    incluyeMateriales: true,
    garantia: '30 días',
    direccionReferencia: 'Calle 123, Col. Centro, CDMX',
    modalidadesCobro: ['Por mes'],
    costo: 20000,
    disponibilidad: [
      { dia: 'Lunes a Viernes', horario: '9:00 AM - 6:00 PM' },
    ],
    evidencias: [
      'https://via.placeholder.com/150',
      'https://via.placeholder.com/150',
      'https://via.placeholder.com/150',
      'https://via.placeholder.com/150',
    ],
  },
  {
    titulo: 'Analista de Datos',
    prestamista: 'Ana Martínez',
    imagen: img,
    categoria: 'Análisis',
    alcaldia: 'Coyoacán',
    descripcion: 'Buscamos un analista de datos con experiencia en SQL y herramientas de visualización.',
    fecha: '2023-10-04',
    incluyeMateriales: false,
    garantia: null,
    direccionReferencia: null,
    modalidadesCobro: ['Por hora'],
    costo: 300,
    disponibilidad: [
      { dia: 'Sábado', horario: '10:00 AM - 2:00 PM' },
    ],
    evidencias: [
      'https://via.placeholder.com/150',
    ],
  },
  {
    titulo: 'Especialista en Marketing Digital',
    prestamista: 'Luis Hernández',
    imagen: img,
    categoria: 'Marketing',
    alcaldia: 'Gustavo A. Madero',
    descripcion: 'Especialista en marketing digital con experiencia en SEO y campañas de publicidad online.',
    fecha: '2023-10-05',
    incluyeMateriales: true,
    garantia: '7 días',
    direccionReferencia: 'Av. Eduardo Molina 789, Col. Aragón, CDMX',
    modalidadesCobro: ['Por día'],
    costo: 1500,
    disponibilidad: [
      { dia: 'Lunes a Viernes', horario: '8:00 AM - 4:00 PM' },
    ],
    evidencias: [
      'https://via.placeholder.com/150',
      'https://via.placeholder.com/150',
    ],
  },
  // Agrega más trabajos según sea necesario
];